FROM node:23.5 AS runtime
WORKDIR /app

COPY . .

ARG STRIPE_SECRET_KEY
ARG PUBLIC_STRIPE_KEY

ENV STRIPE_SECRET_KEY ${STRIPE_SECRET_KEY}
ENV PUBLIC_STRIPE_KEY ${PUBLIC_STRIPE_KEY}

RUN npm install
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
CMD node ./dist/server/entry.mjs
