FROM node:23.5 AS runtime
WORKDIR /app

COPY . .

ARG ATTAKK_BACKEND_API_URL
ARG CHECKOUT_METHOD
ARG PUBLIC_STRIPE_KEY
ARG STRIPE_SECRET_KEY
ARG ORDERING_ENABLED

ENV ATTAKK_BACKEND_API_URL=${ATTAKK_BACKEND_API_URL}
ENV CHECKOUT_METHOD=${CHECKOUT_METHOD}
ENV PUBLIC_STRIPE_KEY=${PUBLIC_STRIPE_KEY}
ENV STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
ENV ORDERING_ENABLED=${ORDERING_ENABLED}

RUN npm install
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
CMD node ./dist/server/entry.mjs
